'use client'
import { FormEvent, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

export default function LoginPage() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState('')
  async function submit(event: FormEvent) { event.preventDefault(); setMessage(''); const { error } = await createClient().auth.signInWithPassword({ email, password }); if (error) { setMessage(error.message.toLowerCase().includes('confirm') ? 'Please confirm your email before signing in.' : 'Invalid email or password.'); return }; window.location.href = '/dashboard' }
  return <main className="grid min-h-screen place-items-center bg-muted/40 px-5"><form onSubmit={submit} className="flex w-full max-w-md flex-col gap-5 rounded-2xl border border-border bg-card p-7 shadow-sm"><div><p className="font-mono text-xs font-bold uppercase tracking-widest text-primary">TravelTrade Exchange</p><h1 className="mt-3 text-3xl font-semibold tracking-tight">Welcome back</h1><p className="mt-2 text-sm text-muted-foreground">Sign in to manage your travel work.</p></div><label className="flex flex-col gap-2 text-sm font-medium">Email<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="rounded-lg border border-input bg-background px-3 py-2.5 outline-none focus:ring-2 focus:ring-ring" /></label><label className="flex flex-col gap-2 text-sm font-medium">Password<input required type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="rounded-lg border border-input bg-background px-3 py-2.5 outline-none focus:ring-2 focus:ring-ring" /></label>{message && <p role="alert" className="text-sm text-destructive">{message}</p>}<button className="rounded-lg bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground">Sign in</button><a href="/auth/sign-up" className="text-center text-sm text-primary underline-offset-4 hover:underline">Create an account</a></form></main>
}
